stages:
  - setup
  - build
  - test
  - deploy

setup:
  stage: setup
  tags:
    - self-hosted
  script:
    - echo "Setting up environment..."
    - sudo apt update && sudo apt install -y nodejs npm postgresql-client
    - node -v && npm -v

build:
  stage: build
  tags:
    - self-hosted
  script:
    - cd frontend && npm install && npm run build
    - cd ../backend && npm install

test:
  stage: test
  tags:
    - self-hosted
  script:
    - cd backend && npm test

deploy:
  stage: deploy
  tags:
    - self-hosted
  script:
    - echo "Deploying application..."
    
    # Stop existing app (if running)
    - pm2 stop all || true
    - pm2 delete all || true

    # Deploy Backend
    - cd backend
    - npm install
    - pm2 start server.js --name backend

    # Deploy Frontend
    - cd ../frontend
    - npm install
    - npm run build
    - sudo rm -rf /var/www/html/*
    - sudo cp -r dist/* /var/www/html/
    
    # Restart services
    - pm2 save
    - echo "Deployment successful!"
